AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  Api:
    Properties:
      DefinitionBody:
        info:
          title: serverless-app
          version: '1.0'
        paths:
          /images:
            get:
              responses: {}
              security:
              - Cognito_Custom_Authorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${getImages.Arn}/invocations
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
              x-amazon-apigateway-integration:
                requestTemplates:
                  application/json: "{\n  \"statusCode\" : 200\n}\n"
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''GET,
                        POST, PUT, DELETE'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}

                        '
                    statusCode: '200'
                type: mock
            post:
              responses: {}
              security:
              - Cognito_Custom_Authorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${postImages.Arn}/invocations
            put:
              responses: {}
              security:
              - Cognito_Custom_Authorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${updateImage.Arn}/invocations
          /images/{id}:
            delete:
              responses: {}
              security:
              - Cognito_Custom_Authorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${deleteImageById.Arn}/invocations
            get:
              responses: {}
              security:
              - Cognito_Custom_Authorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${getImageById.Arn}/invocations
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
              x-amazon-apigateway-integration:
                requestTemplates:
                  application/json: "{\n  \"statusCode\" : 200\n}\n"
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''GET,
                        POST, PUT, DELETE'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}

                        '
                    statusCode: '200'
                type: mock
        schemes:
        - https
        securityDefinitions:
          Cognito_Custom_Authorizer:
            in: header
            name: Authorization
            type: apiKey
            x-amazon-apigateway-authorizer:
              providerARNs:
              - arn:aws:cognito-idp:ap-northeast-1:251699169519:userpool/ap-northeast-1_Xm26yt9iF
              type: cognito_user_pools
            x-amazon-apigateway-authtype: cognito_user_pools
        swagger: '2.0'
      StageName: Prod
    Type: AWS::Serverless::Api
  deleteImageById:
    Properties:
      CodeUri: s3://mitsu-serverless-book-sample-spa/e426778dabd04b65fad11d5078436275
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: mitsu-serverless-app-photos
          TABLE_NAME: mitsu-photos
      Handler: delete-image-by-id.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::251699169519:role/lambda-dynamobd-access
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
  deleteImageByIdPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: deleteImageById
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  getImageById:
    Properties:
      CodeUri: s3://mitsu-serverless-book-sample-spa/109d764026f3bb2998c99d0f00802691
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: mitsu-serverless-app-photos
          TABLE_NAME: mitsu-photos
      Handler: get-image-by-id.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::251699169519:role/lambda-dynamobd-access
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
  getImageByIdPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: getImageById
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  getImages:
    Properties:
      CodeUri: s3://mitsu-serverless-book-sample-spa/38493d1d36089f7fd404fd27f1e6ea5a
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: mitsu-serverless-app-photos
          TABLE_NAME: mitsu-photos
      Handler: get-images.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::251699169519:role/lambda-dynamobd-access
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
  getImagesPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: getImages
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  postImages:
    Properties:
      CodeUri: s3://mitsu-serverless-book-sample-spa/64bcddc406995d7e000df2aacef2b584
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: mitsu-serverless-app-photos
          TABLE_NAME: mitsu-photos
      Handler: post-images.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::251699169519:role/lambda-dynamobd-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  postImagesPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: postImages
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  updateImage:
    Properties:
      CodeUri: s3://mitsu-serverless-book-sample-spa/ce9d9c0ac1457d91f0cec6f6398bf63a
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: mitsu-serverless-app-photos
          TABLE_NAME: mitsu-photos
      Handler: update-image.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::251699169519:role/lambda-dynamobd-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  updateImagePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: updateImage
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
Transform: AWS::Serverless-2016-10-31
